
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.72.128:3306/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
wechat:
  mpAppId: wx887409d02e8241eb
  mpAppSecret: 11d294dd5a3bb437bddf559e9e127ad0

  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://wxh3zh.natappfree.cc /sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://gpmjcf.natappfree.cc
  sell: http://gpmjcf.natappfree.cc
  wechatOpenAuthorize: http://gpmjcf.natappfree.cc