spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: business-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.202:8848
    sentinel:
      transport:
        dashboard: localhost:8888

feign:
  sentinel:
    enabled: true

server:
  port: 12000

dubbo:
  scan:
    base-packages: com.funtl.myshop.business.controller
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.43.202:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"